(()=>{
'use strict';
state.labBook=state.labBook||{};
let lbSelected=state.last||1,lbStep=0,saveTimer=0;
const stepNames=['Identity','Set-up','Variables & method','Safety','Raw data','Uncertainty & maths','Graph','Conclusion & evaluation','Evidence & reflection'];
const schemas={
1:['Vibrating length / m','Tension / N','Resonant frequency / Hz','Repeat / mean'],
2:['D / m or order n','Fringe span / position','Processed spacing / sinθ','Notes'],
3:['Fall distance h / m','Time 1 / s','Time 2 / s','Mean time / s'],
4:['Force / N','Wire diameter / mm','Extension / mm','Processed stress / strain'],
5:['Wire length / m','p.d. / V','Current / A','Resistance / Ω'],
6:['External resistance / Ω','Current / A','Terminal p.d. / V','Notes'],
7:['Length or mass','Number of cycles','Total time / s','Period / s'],
8:['Hanging mass / g or T / °C','Volume / mL or air length / cm','Pressure / kPa or T / K','Processed value'],
9:['Time / s','Capacitor p.d. / V','ln term','Notes'],
10:['Current / A','Active length / m','Balance change / g','Force / N'],
11:['Angle / °','Induced emf amplitude / V','cosθ','Notes'],
12:['Distance / cm','Count time / s','Counts','Corrected rate / min⁻¹']
};
const focus={
1:['Measure the vibrating length between effective end points.','Keep tension and linear density fixed when investigating length.','State how resonance was identified and repeated.'],
2:['Measure several fringes rather than one where possible.','Define D from the slit/grating plane to the screen.','For the grating, record order n and the angle convention.'],
3:['Measure the vertical fall distance from consistent reference points.','Repeat electronic timings and calculate a mean.','Use h against t²; gradient = g/2.'],
4:['Take several diameter readings in different positions/orientations.','Record loading and unloading where appropriate.','Calculate stress and strain before finding Young modulus.'],
5:['Record L, V and I for each point and calculate R=V/I.','Avoid heating changing the resistance.','Use R against L and relate gradient to ρ/A.'],
6:['Record paired I and V values only while the switch is closed.','Open the switch between readings.','V against I gives emf from intercept and r from gradient magnitude.'],
7:['Time many oscillations and divide by the number of cycles.','Keep pendulum amplitude small.','Use T² against L or T² against m.'],
8:['Boyle: record total hanging mass, seal diameter, syringe volume and calculated pressure.','Use P = Patm − mg/A for the AQA hanging-mass geometry.','Charles: allow thermal equilibrium and use kelvin.'],
9:['Start timing consistently with switching.','Record enough points to show the exponential change.','For discharge use ln(V) against t.'],
10:['Use only the wire length inside the magnetic field as active length.','Convert balance change to force using Δmg.','Change one variable at a time in F=BIL.'],
11:['Keep the search coil centred while changing angle.','Hold the selected angle while reading the alternating signal.','Record the angle convention and oscilloscope amplitude.'],
12:['Simulation-only: record background separately and correct the count rate.','Use long enough count times to reduce fractional uncertainty.','Do not record or practise source-handling procedures in this app.']
};
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function pById(id){return practicals.find(p=>p.id===+id)||practicals[0];}
function entry(id){const k=String(id);const e=state.labBook[k]||(state.labBook[k]={});e.date=e.date||new Date().toISOString().slice(0,10);e.completed=e.completed||{};e.rawRows=e.rawRows||[];e.uncRows=e.uncRows||[];e.evalRows=e.evalRows||[];e.setupChecks=e.setupChecks||{};return e;}
function saveNow(){save();const s=document.querySelector('#lbSaveStatus');if(s){s.innerHTML='<i></i>Saved on this device';clearTimeout(saveTimer);saveTimer=setTimeout(()=>{if(s)s.innerHTML='<i></i>Autosave on';},900);}}
function progress(id){const e=entry(id);let n=0;for(let i=0;i<9;i++)if(e.completed[i])n++;return {n,pct:Math.round(n/9*100)};}
function totalProgress(){let done=0;practicals.forEach(p=>done+=progress(p.id).n);return {done,total:108,pct:Math.round(done/108*100)};}
function recordedData(id){const sets=[];Object.entries(state.data||{}).forEach(([k,rows])=>{if(!k.startsWith(id+'_')||!Array.isArray(rows)||!rows.length)return;const mode=+k.split('_')[1]||0;sets.push({mode,rows});});return sets;}
function dataPreview(id){const p=pById(id),sets=recordedData(id);if(!sets.length)return 'No simulation readings recorded yet.';return sets.map(s=>`${p.modes[s.mode]||'Mode '+(s.mode+1)}\n${p.x}\t${p.y}\n${s.rows.map(r=>`${fmt(r.x)}\t${fmt(r.y)}`).join('\n')}`).join('\n\n');}
function field(e,key,label,hint,rows=5){return `<label class="lb-field"><span>${label}</span><small>${hint}</small><textarea rows="${rows}" data-lbf="${key}">${esc(e[key]||'')}</textarea></label>`;}
function textInput(e,key,label,hint,type='text'){return `<label class="lb-field"><span>${label}</span><small>${hint}</small><input type="${type}" data-lbf="${key}" value="${esc(e[key]||'')}"></label>`;}
function setupPanel(id,e){const g=window.AQA_SETUP_GUIDE?.[id],checks=g?.checks||[];return `<div class="lb-panel"><div class="lb-section-title"><h3>AQA set-up check</h3><span class="lb-required">check before writing</span></div><p class="lb-help">${esc(g?.summary||'Record the arrangement actually used in your lesson.')}</p><div class="lb-checklist">${checks.map((x,i)=>`<label class="lb-check"><input type="checkbox" data-setup-check="${i}" ${e.setupChecks[i]?'checked':''}><span>${esc(x)}</span></label>`).join('')}</div></div>`;}
function rowsTable(id,e){const heads=schemas[id]||['Independent variable','Dependent variable','Processed value','Notes'];if(!e.rawRows.length)e.rawRows.push(['','','','']);return `<div class="lb-table-wrap"><table class="lb-table"><thead><tr><th>#</th>${heads.map(h=>`<th>${esc(h)}</th>`).join('')}<th></th></tr></thead><tbody>${e.rawRows.map((r,ri)=>`<tr><td>${ri+1}</td>${heads.map((_,ci)=>`<td><input data-raw-row="${ri}" data-raw-col="${ci}" value="${esc(r[ci]||'')}"></td>`).join('')}<td><button class="tiny-btn" data-del-raw="${ri}" aria-label="Remove row">×</button></td></tr>`).join('')}</tbody></table></div><div class="lb-row-actions"><button class="secondary-btn" id="lbAddRaw">+ Add row</button><button class="secondary-btn" id="lbImportSim">Import simulation readings</button></div>`;}
function uncTable(e){if(!e.uncRows.length)e.uncRows.push({q:'',instrument:'',resolution:'',uncertainty:'',note:''});return `<div class="lb-table-wrap"><table class="lb-table"><thead><tr><th>Quantity</th><th>Instrument</th><th>Resolution</th><th>Uncertainty</th><th>How used</th><th></th></tr></thead><tbody>${e.uncRows.map((r,i)=>`<tr>${['q','instrument','resolution','uncertainty','note'].map(k=>`<td><input data-unc-row="${i}" data-unc-key="${k}" value="${esc(r[k]||'')}"></td>`).join('')}<td><button class="tiny-btn" data-del-unc="${i}">×</button></td></tr>`).join('')}</tbody></table></div><div class="lb-row-actions"><button class="secondary-btn" id="lbAddUnc">+ Add uncertainty</button></div>`;}
function evalTable(e){if(!e.evalRows.length)e.evalRows.push({limitation:'',effect:'',improvement:''});return `<div class="lb-table-wrap"><table class="lb-table"><thead><tr><th>Limitation / issue</th><th>Effect on data/result</th><th>Specific improvement</th><th></th></tr></thead><tbody>${e.evalRows.map((r,i)=>`<tr>${['limitation','effect','improvement'].map(k=>`<td><textarea data-eval-row="${i}" data-eval-key="${k}">${esc(r[k]||'')}</textarea></td>`).join('')}<td><button class="tiny-btn" data-del-eval="${i}">×</button></td></tr>`).join('')}</tbody></table></div><div class="lb-row-actions"><button class="secondary-btn" id="lbAddEval">+ Add evaluation point</button></div>`;}
function stepHtml(id,step){const p=pById(id),e=entry(id),f=focus[id]||[];let main='',side='';
 if(step===0){main=`<div class="lb-panel"><div class="lb-two">${textInput(e,'date','Date','Date the practical record.','date')}${textInput(e,'studentRef','Class / page / file reference','Optional cross-reference used by your school or college.')}</div>${field(e,'aim','Aim / objective','State the relationship or quantity being investigated; do not just write the practical title.',4)}</div>`;side=`<div class="lb-panel"><h3>What a strong opening contains</h3><div class="lb-checklist"><span>• A clear practical title and date.</span><span>• A specific aim linked to measurable quantities.</span><span>• Relevant AQA apparatus/technique codes: <b>${p.at.join(' · ')}</b>.</span></div></div>`;}
 if(step===1){main=setupPanel(id,e)+`<div class="lb-panel">${field(e,'setup','Your apparatus / labelled set-up record','Describe or sketch the arrangement actually used. Include meter ranges, key distances, reference points and settings where relevant.',7)}</div>`;side=`<div class="lb-panel"><h3>Student check</h3><p class="lb-help">A set-up drawing should make the measurement geometry obvious. Label the parts that define the quantities you calculate later.</p><div class="lb-callout">${esc(f[0]||'Record the measurement geometry clearly.')}</div></div>`;}
 if(step===2){main=`<div class="lb-panel"><div class="lb-three">${field(e,'independent','Independent variable','What you deliberately change.',3)}${field(e,'dependent','Dependent variable','What you measure as the response.',3)}${field(e,'controls','Control variables','What must stay constant and how.',3)}</div>${field(e,'method','Method as actually carried out','Write the sequence, settings and changes actually used. Include repeats and how readings were taken.',8)}</div>`;side=`<div class="lb-panel"><h3>Method focus</h3><div class="lb-callout">${esc(f[1]||'Keep important control variables constant.')}</div><p class="lb-help">A lab book is a live record. If the method changed, record the change later rather than rewriting history.</p></div>`;}
 if(step===3){main=`<div class="lb-panel">${field(e,'safety','Safety / risk controls','Record the controls your teacher/technician required and the precautions relevant to the apparatus actually used.',7)}</div>`;side=`<div class="lb-panel"><h3>Keep this specific</h3><p class="lb-help">Avoid a generic list. Link each control to the equipment or hazard in the real practical. Your school/college risk assessment and staff instructions take priority.</p>${id===12?'<div class="lb-callout warn">This app keeps Practical 12 simulation-only and does not provide source-handling instructions.</div>':''}</div>`;}
 if(step===4){main=`<div class="lb-panel"><div class="lb-section-title"><h3>Raw data table</h3><span class="lb-required">record during practical</span></div><p class="lb-help">Use units in headings. Keep raw readings distinct from later processed quantities.</p>${rowsTable(id,e)}</div><div class="lb-panel">${field(e,'observations','Observations / anomalies','Record useful qualitative observations, unexpected behaviour, anomalous points and what happened during the run.',5)}</div>`;side=`<div class="lb-panel"><h3>Simulation data available</h3><pre class="lb-data-preview">${esc(dataPreview(id))}</pre><p class="lb-help">Importing simulation data is for revision/practice. Your real lab book should contain the readings you actually obtained in class.</p></div>`;}
 if(step===5){main=`<div class="lb-panel"><h3>Measurement uncertainty</h3><p class="lb-help">Record instrument resolution, estimated uncertainty and where repeat spread matters.</p>${uncTable(e)}</div><div class="lb-panel">${field(e,'calculations','Calculations / processing','Show equations, substitutions, units and processed values. Keep enough working that another reader can follow your reasoning.',8)}</div>`;side=`<div class="lb-panel"><h3>Uncertainty focus</h3><div class="lb-callout">${esc(f[2]||'Link uncertainty to the measurements that dominate the final result.')}</div><p class="lb-help">Where a calculation uses powers or products, explain how measurement uncertainty affects the processed quantity.</p></div>`;}
 if(step===6){main=`<div class="lb-panel">${field(e,'graph','Graph / data-processing record','Write the axes and units, transformation, best-fit method, gradient/intercept and what physical quantity the graph gives.',8)}${field(e,'graphResult','Gradient / intercept / result from graph','Record the numerical quantity extracted from the graph with units and sensible precision.',4)}</div>`;side=`<div class="lb-panel"><h3>For this practical</h3><div class="lb-callout">${esc(({
1:'Use the linearised relationship appropriate to the variable being changed.',2:'Young slits: use fringe spacing carefully. Grating: use nλ = d sinθ.',3:'Plot h against t²; gradient = g/2.',4:'Plot stress against strain in the elastic region.',5:'Plot R against L; gradient = ρ/A.',6:'Plot V against I; intercept = emf and gradient = −r.',7:'Plot T² against L or m.',8:'Boyle: plot 1/V against P. Charles: use absolute temperature.',9:'For discharge, plot ln(V) against t.',10:'Test F against I, L or B one variable at a time.',11:'Plot emf amplitude against the chosen trigonometric function.',12:'Plot corrected count rate against 1/r².'}[id])||'State why your graph tests the physics model.')}</div></div>`;}
 if(step===7){main=`<div class="lb-panel">${field(e,'conclusion','Conclusion','Answer the aim using your evidence. Quote the measured relationship/result with units where appropriate and connect it to the expected physics.',6)}</div><div class="lb-panel"><h3>Evaluation table</h3><p class="lb-help">Make each improvement solve a specific limitation rather than writing vague phrases such as “be more careful”.</p>${evalTable(e)}</div>`;side=`<div class="lb-panel"><h3>Evaluation quality check</h3><div class="lb-checklist"><span>• Identify whether effects are random or systematic where possible.</span><span>• Refer to scatter, anomalies or uncertainty evidence.</span><span>• Explain the direction/effect on the result when you can.</span><span>• Link every improvement to a named limitation.</span></div></div>`;}
 if(step===8){main=`<div class="lb-panel">${field(e,'changes','Changes made during the practical','Record method changes, repeated runs, rejected readings and the reason for them.',5)}${field(e,'references','References / cross-references','Record worksheets, data files, page references or other sources used.',4)}${field(e,'reflection','Practical-skills reflection','What skill improved? What would you do differently next time? What evidence could your teacher use when judging practical competence?',6)}</div>`;side=`<div class="lb-panel"><h3>Evidence record</h3><div class="lb-evidence"><div><span>Followed procedures</span><b>${e.completed[2]?'✓':'—'}</b></div><div><span>Used apparatus / measurements</span><b>${e.completed[1]&&e.completed[4]?'✓':'—'}</b></div><div><span>Recorded data with units</span><b>${e.completed[4]?'✓':'—'}</b></div><div><span>Processed data / uncertainty</span><b>${e.completed[5]&&e.completed[6]?'✓':'—'}</b></div><div><span>Evaluated evidence</span><b>${e.completed[7]?'✓':'—'}</b></div></div><p class="lb-help">This is a student organisation aid only. Practical Endorsement assessment/sign-off remains with your school or college.</p></div>`;}
 return `<div class="lb-step-content"><div class="lb-main">${main}</div><aside class="lb-side">${side}</aside></div>`;
}
function dashboard(){const overall=totalProgress();return `<div class="lb-dashboard"><section class="lb-hero"><span class="eyebrow">AQA PRACTICAL RECORD WORKSPACE</span><h2>Your Physics Lab Book</h2><p>Build a clear record of what you actually did, measured, calculated and concluded. The workflow separates raw data from processing and keeps set-up, uncertainty and evaluation visible.</p></section><section class="lb-summary"><small>Overall recording progress</small><strong>${overall.pct}%</strong><div class="lb-progressbar"><i style="width:${overall.pct}%"></i></div><span>${overall.done} of ${overall.total} recording steps marked complete</span></section></div><div class="lb-practical-grid">${practicals.map(p=>{const pr=progress(p.id);return `<article class="lb-card" data-lb-open="${p.id}"><div class="lb-card-top"><span class="lb-badge">Practical ${p.id}</span><span class="lb-mini-progress">${pr.pct}%</span></div><h3>${esc(p.title)}</h3><small>${esc(p.topic)} · ${pr.n}/9 sections complete</small><div class="lb-progressbar"><i style="width:${pr.pct}%"></i></div></article>`}).join('')}</div>`;}
function renderLabBookV2(){const root=document.querySelector('#labBookRoot');if(!root)return;const p=pById(lbSelected),e=entry(lbSelected),pr=progress(lbSelected);root.innerHTML=`<div class="labbook-v2">${dashboard()}<section class="lb-entry"><div class="lb-entry-head"><div><span class="eyebrow">CURRENT ENTRY</span><h2>Practical ${p.id}: ${esc(p.title)}</h2><div class="lb-save-status" id="lbSaveStatus"><i></i>Autosave on</div></div><div class="lb-toolbar"><select id="lbSelect">${practicals.map(x=>`<option value="${x.id}" ${x.id===lbSelected?'selected':''}>${x.id}. ${esc(x.title)}</option>`).join('')}</select><button class="secondary-btn" id="lbOpenSim">Open simulation</button><button class="secondary-btn" id="lbPrint">Print / Save PDF</button><button class="secondary-btn" id="lbBackup">Export backup</button></div></div><div class="lb-progressbar"><i style="width:${pr.pct}%"></i></div><div class="lb-stepper">${stepNames.map((n,i)=>`<button data-lb-step="${i}" class="${lbStep===i?'active':''} ${e.completed[i]?'done':''}"><span>${i+1}</span>${n}</button>`).join('')}</div>${stepHtml(lbSelected,lbStep)}<div class="lb-nav"><button class="secondary-btn" id="lbPrev" ${lbStep===0?'disabled':''}>← Previous</button><label class="lb-check"><input id="lbDone" type="checkbox" ${e.completed[lbStep]?'checked':''}><span>Mark this section complete</span></label><button class="primary-btn" id="lbNext">${lbStep===8?'Back to section 1':'Next →'}</button></div></section></div>`;bind();}
function bind(){const e=entry(lbSelected);
 document.querySelectorAll('[data-lb-open]').forEach(x=>x.onclick=()=>{lbSelected=+x.dataset.lbOpen;lbStep=0;renderLabBookV2();});
 const sel=document.querySelector('#lbSelect');if(sel)sel.onchange=()=>{lbSelected=+sel.value;lbStep=0;renderLabBookV2();};
 document.querySelectorAll('[data-lb-step]').forEach(x=>x.onclick=()=>{lbStep=+x.dataset.lbStep;renderLabBookV2();});
 document.querySelectorAll('[data-lbf]').forEach(x=>x.oninput=()=>{e[x.dataset.lbf]=x.value;saveNow();});
 document.querySelectorAll('[data-setup-check]').forEach(x=>x.onchange=()=>{e.setupChecks[x.dataset.setupCheck]=x.checked;saveNow();});
 document.querySelectorAll('[data-raw-row]').forEach(x=>x.oninput=()=>{const r=+x.dataset.rawRow,c=+x.dataset.rawCol;e.rawRows[r]=e.rawRows[r]||['','','',''];e.rawRows[r][c]=x.value;saveNow();});
 document.querySelectorAll('[data-unc-row]').forEach(x=>x.oninput=()=>{const r=+x.dataset.uncRow,k=x.dataset.uncKey;e.uncRows[r]=e.uncRows[r]||{};e.uncRows[r][k]=x.value;saveNow();});
 document.querySelectorAll('[data-eval-row]').forEach(x=>x.oninput=()=>{const r=+x.dataset.evalRow,k=x.dataset.evalKey;e.evalRows[r]=e.evalRows[r]||{};e.evalRows[r][k]=x.value;saveNow();});
 document.querySelectorAll('[data-del-raw]').forEach(x=>x.onclick=()=>{e.rawRows.splice(+x.dataset.delRaw,1);saveNow();renderLabBookV2();});
 document.querySelectorAll('[data-del-unc]').forEach(x=>x.onclick=()=>{e.uncRows.splice(+x.dataset.delUnc,1);saveNow();renderLabBookV2();});
 document.querySelectorAll('[data-del-eval]').forEach(x=>x.onclick=()=>{e.evalRows.splice(+x.dataset.delEval,1);saveNow();renderLabBookV2();});
 const addRaw=document.querySelector('#lbAddRaw');if(addRaw)addRaw.onclick=()=>{e.rawRows.push(['','','','']);saveNow();renderLabBookV2();};
 const addUnc=document.querySelector('#lbAddUnc');if(addUnc)addUnc.onclick=()=>{e.uncRows.push({q:'',instrument:'',resolution:'',uncertainty:'',note:''});saveNow();renderLabBookV2();};
 const addEval=document.querySelector('#lbAddEval');if(addEval)addEval.onclick=()=>{e.evalRows.push({limitation:'',effect:'',improvement:''});saveNow();renderLabBookV2();};
 const imp=document.querySelector('#lbImportSim');if(imp)imp.onclick=()=>{const sets=recordedData(lbSelected);sets.forEach(s=>s.rows.forEach(r=>e.rawRows.push([fmt(r.x),fmt(r.y),'','simulation practice'])));saveNow();renderLabBookV2();};
 const done=document.querySelector('#lbDone');if(done)done.onchange=()=>{e.completed[lbStep]=done.checked;saveNow();renderLabBookV2();};
 const prev=document.querySelector('#lbPrev');if(prev)prev.onclick=()=>{if(lbStep>0){lbStep--;renderLabBookV2();}};
 const next=document.querySelector('#lbNext');if(next)next.onclick=()=>{lbStep=lbStep===8?0:lbStep+1;renderLabBookV2();};
 const sim=document.querySelector('#lbOpenSim');if(sim)sim.onclick=()=>navigate('practical',lbSelected);
 const print=document.querySelector('#lbPrint');if(print)print.onclick=()=>window.print();
 const backup=document.querySelector('#lbBackup');if(backup)backup.onclick=()=>{const blob=new Blob([JSON.stringify({version:2,exported:new Date().toISOString(),labBook:state.labBook},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='AQA-Physics-Lab-Book-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),0);};
}
window.renderLabBook=renderLabBookV2;
const priorNavigateV2=navigate;navigate=function(view,id){const out=priorNavigateV2(view,id);if(view==='labbook'){if(id)lbSelected=+id;setTimeout(renderLabBookV2,0);}return out;};
window.__labBookV2={render:renderLabBookV2,select:id=>{lbSelected=+id;lbStep=0;renderLabBookV2();},progress};
})();